server:
  port: 31450
spring:
  application:
    name: pika-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://localhost
      database: pika_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
pika-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: D:\pika\video\
  ffmpeg-path: D:/code/tools/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe